# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: db98aade2764a0948b8ab6705f1220121990391a7420ffd23071d60828b1c36ac62fb06fba1e52f9ff6fd52876807294155251036441a2c08c2fe66dc6c1eaf2

test:
  secret_key_base: 4d3e710ea6e859be1d5eddde2493d7b6c7a552706c4b40218ee0ba2c9bd92f80c7e19cd1d682b0781f471621bf2104b26e7a62a6387a27368b1a538b9ce47aac

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
